### ISSUE TITLE
Unable to view recieved emails in WebUI

### ISSUE THREAD

**Issue by pcrosthwaite** [djfarrelly/MailDev#236] opened 2018-11-08 03:51 UTC
Currently running maildev on windows server 2016. The webui is accessible, however no email being recieved is shown.

I've run it in verbose mode, and can see the message that an email is recieved. The email file is saved into the temp folder, but nothing in the UI.

I've also noted that the tab is not showing the unread items count, rather the following {{ unreaditems > 0 ? '(' + unreaditems + ')' : ''}}MailDev

Info button is also not working / displaying anything.

Any Ideas?

**Comment by pcrosthwaite** [comment] 2018-11-08 03:52
Running v 1.0.0-rc3 btw

**Comment by LucasBrazi06** [comment] 2018-11-10 17:15
Same issue in Windows env.
I got a log in the console that a new email has been received but nothing in the web interface

**Comment by eharrow** [comment] 2018-11-12 09:07
The developer console in Chrome (windows) has the following error:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:1 Refused to execute script from 'http://localhost:1080/socket.io/socket.io.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
app.js:18 Uncaught ReferenceError: io is not defined
    at app.js:18
    at Object.d [as invoke] (angular.js:3634)
    at angular.js:3483
    at Array.forEach (<anonymous>)
    at q (angular.js:300)
    at Yb (angular.js:3483)
    at c (angular.js:1294)
    at Xb (angular.js:1309)
    at Rc (angular.js:1258)
    at angular.js:20277
```

**Comment by kgeis** [comment] 2018-11-12 17:43
Thank you for the extra detail. I am closing this as a duplicate of #201.

**Closed by kgeis** 2018-11-12 17:43 UTC
