### ISSUE TITLE
Socket.io files missing/not bundled 

### ISSUE THREAD

**Issue by OddBrew** [djfarrelly/MailDev#201] opened 2018-01-03 15:44 UTC
![capture](https://user-images.githubusercontent.com/5788802/34527148-f40dd3ba-f0a4-11e7-816d-cbfc86d52df4.PNG)

- Windows 10 environment
- Installation with default command `npm install -g maildev`
- version 1.0.0-rc3
Had to manually download socket.io.js file and create the directory socket.io in the module.

**Comment by OddBrew** [comment] 2018-01-03 16:37
Actually seems to be a problem about socket.io not listening properly at the server and thus not serving the file.

**Comment by GarathSworn** [comment] 2018-01-10 21:05
The problem appears to be a `path.join()` used in lib/web.js improperly converting /socket.io to \socket.io.

#185 same issue opened by another user.
#195 pull request by a contributor which fixes the problem, but it's months old.

**Comment by mabar** [comment] 2018-01-14 12:01
@djfarrelly Please, could it be fixed? It makes web interface unusable for windows users.

Maildev is requesting adress `http://127.0.0.1:1080/socket.io/socket.io.js` which returns `Cannot GET /socket.io/socket.io.js`

**Comment by volca780** [comment] 2018-01-22 19:45
For fix that, you need to add socket.io in your maildev folder.

Example on windows
Edit ```%appdata%\npm\node_modules\maildev\app\index.html```
Edit this code line
```html
        <script src="components/angular-resource/angular-resource.min.js"></script>
        <script src="components/angular-route/angular-route.min.js"></script>
        <script src="components/angular-sanitize/angular-sanitize.min.js"></script>
        <script src="components/angular-cookies/angular-cookies.min.js"></script>
        <script src="socket.io/socket.io.js"></script>
```
and replace ```socket.io/socket.io.js``` by ```https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.0.4/socket.io.js```

**Comment by aschekatihin** [comment] 2018-07-10 21:46
So, is project abandoned? That's pretty much important fix not pulled for half a year.

**Comment by kgeis** [comment] 2018-07-14 01:14
@aschekatihin, I'm glad you commented. I accidentally closed #204 without pulling. I've reopened, but there are build errors to resolve (perhaps unrelated to the PR) before pulling.

**Comment by rodjf** [comment] 2018-10-01 15:08
I encountered this error by a small mistake in the url : mailDev written with a capital "D".
When I write "maildev" with a small "d", I have not this error any more.

**Comment by oschade** [comment] 2019-02-17 18:51
Still an issue. Seems easy to fix?

**Comment by janbodnar** [comment] 2019-03-04 22:00
I have tried maildev today and the issue is unfortunately still there.

**Comment by oktapodia** [comment] 2019-03-16 00:40
Hello guys, 

Thanks for reporting this problem, the fix has been merged in master and a release on NPM will be push in the next few days.

I'm gonna close this issue at that time

**Closed** 2019-03-22 08:53 UTC
