### ISSUE TITLE
v1.0.0-rc3 not working

### ISSUE THREAD

**Issue by mlaopane** [djfarrelly/MailDev#197] opened 2017-10-11 12:17 UTC
When I try to access the "homepage" at localhost:1080, what I see is the MailDev page but without the main message saying "Now receiving all emails on port 1025", it's all blank.

Nav sections actually show up.

The tab seems to show an Angular expression (with the "unreceived messages" variable).

=> MailDev doesn't catch anything for me.

I've tried the v0.14.0 and it works like a charm.

**Comment by StanleyDeBoer** [comment] 2017-10-19 18:35
I was having the same issue. v1.0.0-rc2 is working for me.

**Comment by cloud-hai-vo** [comment] 2017-10-20 14:39
I got the same issue. 

v0.14.0 works well with windows.

**Comment by kgeis** [comment] 2017-10-27 06:46
This is a duplicate of #185.

**Closed** 2017-11-07 19:53 UTC
Labels: duplicate
